return {
  {
    name = 'amazonq',
    url = 'https://github.com/awslabs/amazonq.nvim.git',
    enabled = false,
    opts = {
      ssoStartUrl = "https://view.awsapps.com/start",
      filetypes = {
        "amazonq",
        "bash",
        "java",
        "python",
        "typescript",
        "javascript",
        "csharp",
        "ruby",
        "kotlin",
        "sh",
        "sql",
        "c",
        "cpp",
        "go",
        "rust",
        "lua",
        "toml",
      },
      inline_suggest = true,
    },
  },
}
